use strum::IntoEnumIterator; // 0.17.1
use strum_macros::EnumIter; // 0.17.1

#[macro_use]
extern crate lazy_static;

#[derive(Debug, PartialEq, Eq, Clone, Copy, EnumIter)]
enum Effect {
    Chameleon,
    CureDisease,
    CureParalysis,
    CurePoison,
    DetectLife,
    Dispel,
    Feather,
    FireShield,
    FortifyStrength,
    FortifyIntelligence,
    FortifyWillpower,
    FortifyAgility,
    FortifySpeed,
    FortifyEndurance,
    FortifyPersonality,
    FortifyLuck,
    FortifyHealth,
    FortifyMagicka,
    FortifyFatigue,
    FrostShield,
    Invisibility,
    Light,
    NightEye,
    ReflectDamage,
    ReflectSpell,
    ResistDisease,
    ResistFire,
    ResistFrost,
    ResistParalysis,
    ResistPoison,
    ResistShock,
    RestoreStrength,
    RestoreIntelligence,
    RestoreWillpower,
    RestoreAgility,
    RestoreSpeed,
    RestoreEndurance,
    RestorePersonality,
    RestoreLuck,
    RestoreHealth,
    RestoreMagicka,
    RestoreFatigue,
    Shield,
    ShockShield,
    WaterBreathing,
    WaterWalking,
    Burden,
    DamageStrength,
    DamageIntelligence,
    DamageWillpower,
    DamageAgility,
    DamageSpeed,
    DamageEndurance,
    DamagePersonality,
    DamageLuck,
    DamageHealth,
    DamageMagicka,
    DamageFatigue,
    DrainStrength,
    DrainIntelligence,
    DrainWillpower,
    DrainAgility,
    DrainSpeed,
    DrainEndurance,
    DrainPersonality,
    DrainLuck,
    DrainHealth,
    DrainMagicka,
    DrainFatigue,
    FireDamage,
    FrostDamage,
    Paralyze,
    ShockDamage,
    Silence,
    WeaknessToFire,
}

impl std::fmt::Display for Effect {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match *self {
            Effect::Chameleon => write!(f, "Chameleon"),
            Effect::CureDisease => write!(f, "Cure Disease"),
            Effect::CureParalysis => write!(f, "Cure Paralysis"),
            Effect::CurePoison => write!(f, "Cure Poison"),
            Effect::DetectLife => write!(f, "Detect Life"),
            Effect::Dispel => write!(f, "Dispel"),
            Effect::Feather => write!(f, "Feather"),
            Effect::FireShield => write!(f, "Fire Shield"),
            Effect::FortifyStrength => write!(f, "Fortify Strength"),
            Effect::FortifyIntelligence => write!(f, "Fortify Intelligence"),
            Effect::FortifyWillpower => write!(f, "Fortify Willpower"),
            Effect::FortifyAgility => write!(f, "Fortify Agility"),
            Effect::FortifySpeed => write!(f, "Fortify Speed"),
            Effect::FortifyEndurance => write!(f, "Fortify Endurance"),
            Effect::FortifyPersonality => write!(f, "Fortify Personality"),
            Effect::FortifyLuck => write!(f, "Fortify Luck"),
            Effect::FortifyHealth => write!(f, "Fortify Health"),
            Effect::FortifyMagicka => write!(f, "Fortify Magicka"),
            Effect::FortifyFatigue => write!(f, "Fortify Fatigue"),
            Effect::FrostShield => write!(f, "Frost Shield"),
            Effect::Invisibility => write!(f, "Invisibility"),
            Effect::Light => write!(f, "Light"),
            Effect::NightEye => write!(f, "Night Eye"),
            Effect::ReflectDamage => write!(f, "Reflect Damage"),
            Effect::ReflectSpell => write!(f, "Reflect Spell"),
            Effect::ResistDisease => write!(f, "Resist Disease"),
            Effect::ResistFire => write!(f, "Resist Fire"),
            Effect::ResistFrost => write!(f, "Resist Frost"),
            Effect::ResistParalysis => write!(f, "Resist Paralysis"),
            Effect::ResistPoison => write!(f, "Resist Poison"),
            Effect::ResistShock => write!(f, "Resist Shock"),
            Effect::RestoreStrength => write!(f, "Restore Strength"),
            Effect::RestoreIntelligence => write!(f, "Restore Intelligence"),
            Effect::RestoreWillpower => write!(f, "Restore Willpower"),
            Effect::RestoreAgility => write!(f, "Restore Agility"),
            Effect::RestoreSpeed => write!(f, "Restore Speed"),
            Effect::RestoreEndurance => write!(f, "Restore Endurance"),
            Effect::RestorePersonality => write!(f, "Restore Personality"),
            Effect::RestoreLuck => write!(f, "Restore Luck"),
            Effect::RestoreHealth => write!(f, "Restore Health"),
            Effect::RestoreMagicka => write!(f, "Restore Magicka"),
            Effect::RestoreFatigue => write!(f, "Restore Fatigue"),
            Effect::Shield => write!(f, "Shield"),
            Effect::ShockShield => write!(f, "Shock Shield"),
            Effect::WaterBreathing => write!(f, "Water Breathing"),
            Effect::WaterWalking => write!(f, "Water Walking"),
            Effect::Burden => write!(f, "Burden"),
            Effect::DamageStrength => write!(f, "Damage Strength"),
            Effect::DamageIntelligence => write!(f, "Damage Intelligence"),
            Effect::DamageWillpower => write!(f, "Damage Willpower"),
            Effect::DamageAgility => write!(f, "Damage Agility"),
            Effect::DamageSpeed => write!(f, "Damage Speed"),
            Effect::DamageEndurance => write!(f, "Damage Endurance"),
            Effect::DamagePersonality => write!(f, "Damage Personality"),
            Effect::DamageLuck => write!(f, "Damage Luck"),
            Effect::DamageHealth => write!(f, "Damage Health"),
            Effect::DamageMagicka => write!(f, "Damage Magicka"),
            Effect::DamageFatigue => write!(f, "Damage Fatigue"),
            Effect::DrainStrength => write!(f, "Drain Strength"),
            Effect::DrainIntelligence => write!(f, "Drain Intelligence"),
            Effect::DrainWillpower => write!(f, "Drain Willpower"),
            Effect::DrainAgility => write!(f, "Drain Agility"),
            Effect::DrainSpeed => write!(f, "Drain Speed"),
            Effect::DrainEndurance => write!(f, "Drain Endurance"),
            Effect::DrainPersonality => write!(f, "Drain Personality"),
            Effect::DrainLuck => write!(f, "Drain Luck"),
            Effect::DrainHealth => write!(f, "Drain Health"),
            Effect::DrainMagicka => write!(f, "Drain Magicka"),
            Effect::DrainFatigue => write!(f, "Drain Fatigue"),
            Effect::FireDamage => write!(f, "Fire Damage"),
            Effect::FrostDamage => write!(f, "Frost Damage"),
            Effect::Paralyze => write!(f, "Paralyze"),
            Effect::ShockDamage => write!(f, "Shock Damage"),
            Effect::Silence => write!(f, "Silence"),
            Effect::WeaknessToFire => write!(f, "Weakness To Fire"),
        }
    }
}

lazy_static! {
    static ref EFFECTS: Vec<Effect> = {
        let mut effects: Vec<Effect> = Effect::iter().collect();
        effects.sort_by_key(|x| x.to_string());
        effects
    };
}

#[derive(Debug, Clone)]
struct Ingredient {
    name: String,
    id: String,
    description: String,
    value: u16,
    weight: f32,
    harvest_chance: f32,
    effects: [Option<Effect>; 4],
}

struct MyApp {
    ingredients: Vec<Ingredient>,
    desired_effects: [Option<Effect>; 4],
    matching_ingredients: Vec<Ingredient>,
}

impl Default for MyApp {
    fn default() -> Self {
        Self {
            ingredients: create_ingredients(),
            desired_effects: [None, None, None, None],
            matching_ingredients: Vec::new(),
        }
    }
}

use eframe::{egui::{self, ScrollArea, TextStyle}, epi};

impl epi::App for MyApp {
    fn name(&self) -> &str {
        "Alchemy Tool"
    }

    fn update(&mut self, ctx: &egui::CtxRef, frame: &epi::Frame) {
        let Self {
            ingredients,
            desired_effects,
            matching_ingredients,
        } = self;

        egui::CentralPanel::default().show(ctx, |ui| {
            ui.heading("Alchemy Tool");

            for (i, effect_label) in (0..4).zip(["First Effect", "Second Effect", "Third Effect", "Fourth Effect"]) {
                egui::ComboBox::from_label(effect_label)
                    .selected_text(format!("{:?}", desired_effects[i]))
                    .show_ui(ui, |ui| {
                        ui.selectable_value(
                            &mut desired_effects[i],
                            None,
                            "None",
                        );
                        for effect in EFFECTS.iter().cloned() {
                            ui.selectable_value(
                                &mut desired_effects[i],
                                Some(effect),
                                effect.to_string(),
                            );
                        }
                    });
                
                    ui.end_row();
            }

            ui.separator();

            if ui.button("Find Ingredients").clicked() {
                // Find Ingredients
                *matching_ingredients = ingredients
                    .iter()
                    .filter(|ingredient| {
                        for desired_effect in desired_effects.iter().cloned() {
                            if desired_effect == None {
                                continue;
                            }
                            // Only matching against one effect
                            if ingredient.effects.contains(&desired_effect) {
                                return true;
                            }
                            // if !ingredient.effects.contains(&desired_effect) {
                            //     return false;
                            // }
                        }

                        false
                        // true
                    })
                    .cloned()
                    .collect();

                println!("{:#?}", matching_ingredients);
            }

            ui.separator();

            ui.label("Matching Ingredients");
            ui.end_row();
            let num_rows = matching_ingredients.len();
            ScrollArea::vertical().auto_shrink([false; 2]).show_rows(
                ui,
                ui.fonts()[TextStyle::Body].row_height(),
                num_rows,
                |ui, row_range| {
                    for row in row_range {
                        let text = format!("{:?}", matching_ingredients[row].name);
                        if ui.selectable_label(false, text).hovered() {
                            // Populate Display
                            ui.separator();
                            egui::Grid::new("Selected Ingredient").striped(true).show(ui, |ui| {
                                ui.label("Name");
                                ui.label("Item ID");
                                ui.label("Description");
                                ui.label("Value");
                                ui.label("Weight");
                                ui.label("Harvest Chance");
                                ui.label("Effects");

                                ui.end_row();

                                ui.label(format!("{}", matching_ingredients[row].name));
                                ui.label(format!("{}", matching_ingredients[row].id));
                                ui.label(format!("{}", matching_ingredients[row].description));
                                ui.label(format!("{}", matching_ingredients[row].value));
                                ui.label(format!("{}", matching_ingredients[row].weight));
                                ui.label(format!("{}", matching_ingredients[row].harvest_chance));
                                ui.label(format!("{:?}", matching_ingredients[row].effects));
                            });
                        }
                    }
                }
            );
        });

        // Resize the native window to be just the size we need it to be:
        frame.set_window_size(ctx.used_size());
    }
}

/*struct Ingredient {
    name: String,
    id: String,
    description: String,
    value: u16,
    weight: f32,
    harvest_chance: f32,
    effects: [Option<Effect>; 4],
} */

fn main() {
    // Using strum to create an iterator on the FlatEffect enum
    let all_flat_effects = {
        let mut temp: Vec<Effect> = Effect::iter().collect();
        temp.sort_by_key(|x| x.to_string());
        temp
    };

    println!("{:?}", all_flat_effects);

    let options = eframe::NativeOptions::default();
    eframe::run_native(Box::new(MyApp::default()), options);
}

fn create_ingredients() -> Vec<Ingredient> {
    vec![
        Ingredient {
            name: String::from("Alkanet Flower"),
            id: String::from("0003365C"),
            description: String::from("Harvested from Alkanet, a fairly common flower in the West Weald."),
            value: 1u16,
            weight: 0.1f32,
            harvest_chance: 80.0f32,
        effects: [Some(Effect::RestoreIntelligence), Some(Effect::ResistPoison), Some(Effect::Light), Some(Effect::DamageFatigue)],
        },
        Ingredient {
            name: String::from("Aloe Vera Leaves"),
            id: String::from("000A7924"),
            description: String::from("Harvested from Aloe Vera, a plant that grows primarily in the Gold Coast."),
            value: 1u16,
            weight: 0.1f32,
            harvest_chance: 80.0f32,
        effects: [Some(Effect::RestoreFatigue), Some(Effect::RestoreHealth), Some(Effect::DamageMagicka), Some(Effect::Invisibility)],
        },
        Ingredient {
            name: String::from("Ambrosia"),
            id: String::from("000704A0"),
            description: String::from("Harvested from reddish-purple colored Mana Bloom, a flower that is normally found only in Mankar Camoran's Paradise."),
            value: 2u16,
            weight: 0.1f32,
            harvest_chance: 80.0f32,
        effects: [Some(Effect::RestoreHealth), None, None, None],
        },
        Ingredient {
            name: String::from("Apple"),
            id: String::from("0003365D"),
            description: String::from("Food, widely found in houses and dining halls."),
            value: 1u16,
            weight: 0.2f32,
            harvest_chance: 0.0f32,
        effects: [Some(Effect::RestoreFatigue), Some(Effect::DamageLuck), Some(Effect::FortifyWillpower), Some(Effect::DamageHealth)],
        },
        Ingredient {
            name: String::from("Arrowroot"),
            id: String::from("0003365E"),
            description: String::from("Harvested from Arrowroot Plant, a plant that is found in the Gold Coast and Nibenay Valley."),
            value: 2u16,
            weight: 0.1f32,
            harvest_chance: 80.0f32,
        effects: [Some(Effect::RestoreAgility), Some(Effect::DamageLuck), Some(Effect::FortifyStrength), Some(Effect::Burden)],
        },
        Ingredient {
            name: String::from("Beef"),
            id: String::from("0003365F"),
            description: String::from("Food, found in a few houses and dining halls."),
            value: 1u16,
            weight: 1.0f32,
            harvest_chance: 0.0f32,
        effects: [Some(Effect::RestoreFatigue), Some(Effect::Shield), Some(Effect::FortifyAgility), Some(Effect::Dispel)],
        },
        Ingredient {
            name: String::from("Bergamot Seeds"),
            id: String::from("000A7933"),
            description: String::from("Harvested from Bergamot, a flower, particularly common along the Orange Road and near Bravil."),
            value: 1u16,
            weight: 0.1f32,
            harvest_chance: 80.0f32,
        effects: [Some(Effect::ResistDisease), Some(Effect::Dispel), Some(Effect::DamageMagicka), Some(Effect::Silence)],
        },
        Ingredient {
            name: String::from("Blackberry"),
            id: String::from("00033663"),
            description: String::from("Food, found in many houses and dining halls. It can also be harvested from Blackberry Bushes found on some farms and in the wild in the West Weald."),
            value: 1u16,
            weight: 0.1f32,
            harvest_chance: 80.0f32,
        effects: [Some(Effect::RestoreFatigue), Some(Effect::ResistShock), Some(Effect::FortifyEndurance), Some(Effect::RestoreMagicka)],
        },
        Ingredient {
            name: String::from("Bloodgrass"),
            id: String::from("00033664"),
            description: String::from("Harvested from Blood Grass, a common plant in the planes of Oblivion."),
            value: 1u16,
            weight: 0.1f32,
            harvest_chance: 50.0f32,
        effects: [Some(Effect::Chameleon), Some(Effect::ResistParalysis), Some(Effect::Burden), Some(Effect::FortifyHealth)],
        },
        Ingredient {
            name: String::from("Boar Meat"),
            id: String::from("00033665"),
            description: String::from("Food, found in several houses and dining halls. Can also be collected from dead Boars, which are randomly found in many outdoors regions."),
            value: 20u16,
            weight: 2.0f32,
            harvest_chance: 0.0f32,
        effects: [Some(Effect::RestoreHealth), Some(Effect::DamageSpeed), Some(Effect::FortifyHealth), Some(Effect::Burden)],
        },
        Ingredient {
            name: String::from("Bog Beacon Asco Cap"),
            id: String::from("0008446C"),
            description: String::from("Harvested from Bog Beacon, a plant found in Blackwood."),
            value: 1u16,
            weight: 0.1f32,
            harvest_chance: 50.0f32,
        effects: [Some(Effect::RestoreMagicka), Some(Effect::Shield), Some(Effect::DamagePersonality), Some(Effect::DamageEndurance)],
        },
        Ingredient {
            name: String::from("Bonemeal*"),
            id: String::from("0001EBFF"),
            description: String::from("Collected from Bones Undead, i.e., skeletons and liches, which are commonly found in all undead dungeons. There is also a rare variant listed below."),
            value: 5u16,
            weight: 0.2f32,
            harvest_chance: 0.0f32,
        effects: [Some(Effect::DamageFatigue), Some(Effect::ResistFire), Some(Effect::FortifyLuck), Some(Effect::NightEye)],
        },
        Ingredient {
            name: String::from("Bread Loaf"),
            id: String::from("00023D89"),
            description: String::from("Food, widely found in houses and dining halls."),
            value: 1u16,
            weight: 0.5f32,
            harvest_chance: 0.0f32,
        effects: [Some(Effect::RestoreFatigue), Some(Effect::DetectLife), Some(Effect::DamageAgility), Some(Effect::DamageStrength)],
        },
        Ingredient {
            name: String::from("Cairn Bolete Cap"),
            id: String::from("0006251E"),
            description: String::from("Harvested from Cairn Bolete, a mushroom found in many caves."),
            value: 1u16,
            weight: 0.1f32,
            harvest_chance: 33.0f32,
        effects: [Some(Effect::RestoreHealth), Some(Effect::DamageIntelligence), Some(Effect::ResistParalysis), Some(Effect::ShockDamage)],
        },
        Ingredient {
            name: String::from("Carrot"),
            id: String::from("00033666"),
            description: String::from("Food, commonly found in houses and dining halls. Can also be harvested from Carrot Plants, which are found growing on many farms."),
            value: 1u16,
            weight: 0.2f32,
            harvest_chance: 80.0f32,
        effects: [Some(Effect::RestoreFatigue), Some(Effect::NightEye), Some(Effect::FortifyIntelligence), Some(Effect::DamageEndurance)],
        },
        Ingredient {
            name: String::from("Cheese Wedge"),
            id: String::from("00033668"),
            description: String::from("Food, commonly found in houses and dining halls."),
            value: 1u16,
            weight: 0.2f32,
            harvest_chance: 0.0f32,
        effects: [Some(Effect::RestoreFatigue), Some(Effect::ResistFire), Some(Effect::FireShield), Some(Effect::DamageAgility)],
        },
        Ingredient {
            name: String::from("Cheese Wheel"),
            id: String::from("00033669"),
            description: String::from("Food, less commonly found in houses and dining halls than Cheese Wedges."),
            value: 1u16,
            weight: 3.0f32,
            harvest_chance: 0.0f32,
        effects: [Some(Effect::RestoreFatigue), Some(Effect::ResistParalysis), Some(Effect::DamageLuck), Some(Effect::FortifyWillpower)],
        },
        Ingredient {
            name: String::from("Cinnabar Polypore Red Cap"),
            id: String::from("0008529C"),
            description: String::from("Harvested from red-colored Cinnabar Polypores, a mushroom that grows sparsely in the West Weald."),
            value: 3u16,
            weight: 0.1f32,
            harvest_chance: 50.0f32,
        effects: [Some(Effect::RestoreAgility), Some(Effect::Shield), Some(Effect::DamagePersonality), Some(Effect::DamageEndurance)],
        },
        Ingredient {
            name: String::from("Cinnabar Polypore Yellow Cap"),
            id: String::from("0008529B"),
            description: String::from("Harvested from yellow-colored Cinnabar Polypores, a mushroom that grows sparsely in the West Weald."),
            value: 3u16,
            weight: 0.1f32,
            harvest_chance: 50.0f32,
        effects: [Some(Effect::RestoreEndurance), Some(Effect::FortifyEndurance), Some(Effect::DamagePersonality), Some(Effect::ReflectSpell)],
        },
        Ingredient {
            name: String::from("Clannfear Claws"),
            id: String::from("0003366A"),
            description: String::from("Collected from dead Clannfears, a type of Daedra common in the Planes of Oblivion."),
            value: 50u16,
            weight: 2.0f32,
            harvest_chance: 0.0f32,
        effects: [Some(Effect::CureDisease), Some(Effect::ResistDisease), Some(Effect::Paralyze), Some(Effect::DamageHealth)],
        },
        Ingredient {
            name: String::from("Clouded Funnel Cap"),
            id: String::from("00084472"),
            description: String::from("Harvested from Clouded Funnel Cap, a mushroom common in mountainous regions (Jerall and Valus Mountains) and Blackwood."),
            value: 1u16,
            weight: 0.1f32,
            harvest_chance: 50.0f32,
        effects: [Some(Effect::RestoreIntelligence), Some(Effect::FortifyIntelligence), Some(Effect::DamageEndurance), Some(Effect::DamageMagicka)],
        },
        Ingredient {
            name: String::from("Columbine Root Pulp"),
            id: String::from("000A7925"),
            description: String::from("Harvested from Columbine, a flower that is common in the West Weald."),
            value: 1u16,
            weight: 0.1f32,
            harvest_chance: 80.0f32,
        effects: [Some(Effect::RestorePersonality), Some(Effect::ResistFrost), Some(Effect::FortifyMagicka), Some(Effect::Chameleon)],
        },
        Ingredient {
            name: String::from("Corn"),
            id: String::from("0003366B"),
            description: String::from("Food, commonly found in houses and dining halls. Can also be harvested from Corn Stalks, which are found growing in many farms."),
            value: 1u16,
            weight: 0.2f32,
            harvest_chance: 80.0f32,
        effects: [Some(Effect::RestoreFatigue), Some(Effect::RestoreIntelligence), Some(Effect::DamageAgility), Some(Effect::ShockShield)],
        },
        Ingredient {
            name: String::from("Crab Meat"),
            id: String::from("0003366C"),
            description: String::from("Collected from dead Mud Crabs, a common nuisance creature found along water shores and in many dungeons."),
            value: 1u16,
            weight: 1.0f32,
            harvest_chance: 0.0f32,
        effects: [Some(Effect::RestoreEndurance), Some(Effect::ResistShock), Some(Effect::DamageFatigue), Some(Effect::FireShield)],
        },
        Ingredient {
            name: String::from("Daedra Heart"),
            id: String::from("0001EC8F"),
            description: String::from("Collected from dead Dremora and Xivilai, both of which are common enemies in the Planes of Oblivion."),
            value: 25u16,
            weight: 2.0f32,
            harvest_chance: 0.0f32,
        effects: [Some(Effect::RestoreHealth), Some(Effect::ShockShield), Some(Effect::DamageMagicka), Some(Effect::Silence)],
        },
        Ingredient {
            name: String::from("Daedra Silk"),
            id: String::from("00033670"),
            description: String::from("Collected from dead Spider Daedra, a type of Daedra common in the Planes of Oblivion."),
            value: 75u16,
            weight: 0.5f32,
            harvest_chance: 0.0f32,
        effects: [Some(Effect::Burden), Some(Effect::NightEye), Some(Effect::Chameleon), Some(Effect::DamageEndurance)],
        },
        Ingredient {
            name: String::from("Daedra Venin"),
            id: String::from("00033671"),
            description: String::from("Collected from dead Spider Daedra, a type of Daedra common in the Planes of Oblivion."),
            value: 75u16,
            weight: 0.2f32,
            harvest_chance: 0.0f32,
        effects: [Some(Effect::Paralyze), Some(Effect::RestoreFatigue), Some(Effect::DamageHealth), Some(Effect::ReflectDamage)],
        },
        Ingredient {
            name: String::from("Daedroth Teeth"),
            id: String::from("00033672"),
            description: String::from("Collected from dead Daedroths, a type of Daedra common in the Planes of Oblivion."),
            value: 65u16,
            weight: 0.5f32,
            harvest_chance: 0.0f32,
        effects: [Some(Effect::NightEye), Some(Effect::FrostShield), Some(Effect::Burden), Some(Effect::Light)],
        },
        Ingredient {
            name: String::from("Dragon's Tongue"),
            id: String::from("00025039"),
            description: String::from("Harvested from Dragon's Tongue Plants, a flower found in a few clusters south of Bravil and more sparsely throughout the West Weald."),
            value: 5u16,
            weight: 0.1f32,
            harvest_chance: 80.0f32,
        effects: [Some(Effect::ResistFire), Some(Effect::DamageHealth), Some(Effect::RestoreHealth), Some(Effect::FireShield)],
        },
        Ingredient {
            name: String::from("Dreugh Wax"),
            id: String::from("00033673"),
            description: String::from("Collected from dead Land Dreughs, a type of monster found outdoors and in monster dungeons at high levels."),
            value: 70u16,
            weight: 1.0f32,
            harvest_chance: 0.0f32,
        effects: [Some(Effect::DamageFatigue), Some(Effect::ResistPoison), Some(Effect::WaterBreathing), Some(Effect::DamageHealth)],
        },
        Ingredient {
            name: String::from("Dryad Saddle Polypore Cap"),
            id: String::from("0008529D"),
            description: String::from("Harvested from Dryad's Saddel [sic] Polypore, a rare mushroom that only grows in a few select locations."),
            value: 10u16,
            weight: 0.1f32,
            harvest_chance: 50.0f32,
        effects: [Some(Effect::RestoreLuck), Some(Effect::ResistFrost), Some(Effect::DamageSpeed), Some(Effect::FrostDamage)],
        },
        Ingredient {
            name: String::from("Ectoplasm"),
            id: String::from("0001EBFE"),
            description: String::from("Collected from dead Ethereal Undead, such as ghosts and wraiths, which are commonly found in all undead dungeons."),
            value: 20u16,
            weight: 0.2f32,
            harvest_chance: 0.0f32,
        effects: [Some(Effect::ShockDamage), Some(Effect::Dispel), Some(Effect::FortifyMagicka), Some(Effect::DamageHealth)],
        },
        Ingredient {
            name: String::from("Elf Cup Cap"),
            id: String::from("0008529E"),
            description: String::from("Harvested from Elf Cups, a mushroom found growing sparsely in the West Weald."),
            value: 5u16,
            weight: 0.1f32,
            harvest_chance: 50.0f32,
        effects: [Some(Effect::DamageWillpower), Some(Effect::CureDisease), Some(Effect::FortifyStrength), Some(Effect::DamageIntelligence)],
        },
        Ingredient {
            name: String::from("Emetic Russula Cap"),
            id: String::from("0008529F"),
            description: String::from("Harvested from Emetic Russula, a mushroom found growing sparsely in the West Weald."),
            value: 4u16,
            weight: 0.1f32,
            harvest_chance: 50.0f32,
        effects: [Some(Effect::RestoreAgility), Some(Effect::Shield), Some(Effect::DamagePersonality), Some(Effect::DamageEndurance)],
        },
        Ingredient {
            name: String::from("Fennel Seeds"),
            id: String::from("000A7926"),
            description: String::from("Harvested from Fennel, a plant found primarily in the northern section of the Gold Coast."),
            value: 5u16,
            weight: 0.1f32,
            harvest_chance: 80.0f32,
        effects: [Some(Effect::RestoreFatigue), Some(Effect::DamageIntelligence), Some(Effect::DamageMagicka), Some(Effect::Paralyze)],
        },
        Ingredient {
            name: String::from("Fire Salts"),
            id: String::from("00033675"),
            description: String::from("Collected from dead Flame Atronachs, a type of Daedra common in the Planes of Oblivion."),
            value: 30u16,
            weight: 0.1f32,
            harvest_chance: 0.0f32,
        effects: [Some(Effect::FireDamage), Some(Effect::ResistFrost), Some(Effect::RestoreMagicka), Some(Effect::FireShield)],
        },
        Ingredient {
            name: String::from("Flax Seeds"),
            id: String::from("000A7927"),
            description: String::from("Harvested from Flax, a common flower found in the West Weald."),
            value: 1u16,
            weight: 0.1f32,
            harvest_chance: 80.0f32,
        effects: [Some(Effect::RestoreMagicka), Some(Effect::Feather), Some(Effect::Shield), Some(Effect::DamageHealth)],
        },
        Ingredient {
            name: String::from("Flour"),
            id: String::from("00033674"),
            description: String::from("Commonly found in grain sacks in kitchens and pantries, but not technically classified as food)."),
            value: 1u16,
            weight: 0.2f32,
            harvest_chance: 0.0f32,
        effects: [Some(Effect::RestoreFatigue), Some(Effect::DamagePersonality), Some(Effect::FortifyFatigue), Some(Effect::ReflectDamage)],
        },
        Ingredient {
            name: String::from("Fly Amanita Cap"),
            id: String::from("00084471"),
            description: String::from("Harvested from Fly Amanita, a common mushroom in cities and in the Great Forest."),
            value: 1u16,
            weight: 0.1f32,
            harvest_chance: 50.0f32,
        effects: [Some(Effect::RestoreAgility), Some(Effect::Burden), Some(Effect::RestoreHealth), Some(Effect::ShockDamage)],
        },
        Ingredient {
            name: String::from("Foxglove Nectar"),
            id: String::from("00033687"),
            description: String::from("Harvested from Foxglove, a common flower in certain parts of the Nibenay Valley and Nibenay Basin."),
            value: 1u16,
            weight: 0.1f32,
            harvest_chance: 80.0f32,
        effects: [Some(Effect::ResistPoison), Some(Effect::ResistParalysis), Some(Effect::RestoreLuck), Some(Effect::ResistDisease)],
        },
        Ingredient {
            name: String::from("Frost Salts"),
            id: String::from("00022E5B"),
            description: String::from("Collected from dead Frost Atronachs, a type of Daedra common in the Planes of Oblivion."),
            value: 60u16,
            weight: 0.1f32,
            harvest_chance: 0.0f32,
        effects: [Some(Effect::FrostDamage), Some(Effect::ResistFire), Some(Effect::Silence), Some(Effect::FrostShield)],
        },
        Ingredient {
            name: String::from("Garlic"),
            id: String::from("00033677"),
            description: String::from("Food, found in several houses and dining halls. It can also be harvested from Garlic Clusters (treated as plants), which are found in some houses' basements (especially in Skingrad)."),
            value: 1u16,
            weight: 0.0f32,
            harvest_chance: 80.0f32,
        effects: [Some(Effect::ResistDisease), Some(Effect::DamageAgility), Some(Effect::FrostShield), Some(Effect::FortifyStrength)],
        },
        Ingredient {
            name: String::from("Ginkgo Leaf"),
            id: String::from("00033678"),
            description: String::from("Cannot be harvested or collected. There are a few guaranteed samples, but otherwise it is randomly found on alchemists and in some containers."),
            value: 1u16,
            weight: 0.1f32,
            harvest_chance: 0.0f32,
        effects: [Some(Effect::RestoreSpeed), Some(Effect::FortifyMagicka), Some(Effect::DamageLuck), Some(Effect::ShockDamage)],
        },
        Ingredient {
            name: String::from("Ginseng"),
            id: String::from("00033679"),
            description: String::from("Harvested from Ginseng Plants, flowers which growly sparsely in the Gold Coast and Nibenay Valley."),
            value: 2u16,
            weight: 0.1f32,
            harvest_chance: 80.0f32,
        effects: [Some(Effect::DamageLuck), Some(Effect::CurePoison), Some(Effect::Burden), Some(Effect::FortifyMagicka)],
        },
        Ingredient {
            name: String::from("Glow Dust"),
            id: String::from("0001EBE8"),
            description: String::from("Collected from dead Will-o-the-Wisps, a type of monster found outdoors and in monster dungeons."),
            value: 40u16,
            weight: 0.1f32,
            harvest_chance: 0.0f32,
        effects: [Some(Effect::RestoreSpeed), Some(Effect::Light), Some(Effect::ReflectSpell), Some(Effect::DamageHealth)],
        },
        Ingredient {
            name: String::from("Grapes"),
            id: String::from("0003367B"),
            description: String::from("Harvested from Grape Vines, which are abundant in several vineyards outside of Skingrad. Can also be found as food in several houses and dining halls."),
            value: 2u16,
            weight: 0.1f32,
            harvest_chance: 80.0f32,
        effects: [Some(Effect::RestoreFatigue), Some(Effect::WaterWalking), Some(Effect::Dispel), Some(Effect::DamageHealth)],
        },
        Ingredient {
            name: String::from("Green Stain Cup Cap"),
            id: String::from("0008446A"),
            description: String::from("Harvested from Green Stain Cups, a mushroom that is common in several regions, but particularly abundant in Blackwood."),
            value: 1u16,
            weight: 0.1f32,
            harvest_chance: 50.0f32,
        effects: [Some(Effect::RestoreFatigue), Some(Effect::DamageSpeed), Some(Effect::ReflectDamage), Some(Effect::DamageHealth)],
        },
        Ingredient {
            name: String::from("Green Stain Shelf Cap"),
            id: String::from("0008529A"),
            description: String::from("Harvested from Green Stain Shelf plants, a rare mushroom that is hard to distinguish from the more common Cup variety."),
            value: 10u16,
            weight: 0.1f32,
            harvest_chance: 50.0f32,
        effects: [Some(Effect::RestoreLuck), Some(Effect::FortifyLuck), Some(Effect::DamageFatigue), Some(Effect::RestoreHealth)],
        },
        Ingredient {
            name: String::from("Ham"),
            id: String::from("0003367C"),
            description: String::from("Food, found in several houses and dining halls."),
            value: 1u16,
            weight: 1.0f32,
            harvest_chance: 0.0f32,
        effects: [Some(Effect::RestoreFatigue), Some(Effect::RestoreHealth), Some(Effect::DamageMagicka), Some(Effect::DamageLuck)],
        },
        Ingredient {
            name: String::from("Harrada"),
            id: String::from("0003367D"),
            description: String::from("Harvested from Harrada Root plants, which are common in the Planes of Oblivion, but also possibly hostile."),
            value: 2u16,
            weight: 0.1f32,
            harvest_chance: 50.0f32,
        effects: [Some(Effect::DamageHealth), Some(Effect::DamageMagicka), Some(Effect::Silence), Some(Effect::Paralyze)],
        },
        Ingredient {
            name: String::from("Imp Gall"),
            id: String::from("0002EE72"),
            description: String::from("Collected from dead Imps, a type of monster found outdoors and in monster dungeons at low levels."),
            value: 15u16,
            weight: 0.2f32,
            harvest_chance: 0.0f32,
        effects: [Some(Effect::FortifyPersonality), Some(Effect::CureParalysis), Some(Effect::DamageHealth), Some(Effect::FireDamage)],
        },
        Ingredient {
            name: String::from("Ironwood Nut"),
            id: String::from("0003367E"),
            description: String::from("Cannot be harvested, collected, or even bought from alchemists. There are 26 guaranteed samples; otherwise they are found randomly in some containers."),
            value: 1u16,
            weight: 0.1f32,
            harvest_chance: 0.0f32,
        effects: [Some(Effect::RestoreIntelligence), Some(Effect::ResistFire), Some(Effect::DamageFatigue), Some(Effect::FortifyHealth)],
        },
        Ingredient {
            name: String::from("Lady's Mantle Leaves"),
            id: String::from("000A7928"),
            description: String::from("Harvested from Lady's Mantle, a flower found near Gottlesfont Priory and in the Gold Coast."),
            value: 5u16,
            weight: 0.1f32,
            harvest_chance: 80.0f32,
        effects: [Some(Effect::RestoreHealth), Some(Effect::DamageEndurance), Some(Effect::NightEye), Some(Effect::Feather)],
        },
        Ingredient {
            name: String::from("Lady's Smock Leaves"),
            id: String::from("000A7929"),
            description: String::from("Harvested from Lady's Smock, a flower common in the West Weald."),
            value: 1u16,
            weight: 0.1f32,
            harvest_chance: 80.0f32,
        effects: [Some(Effect::RestoreIntelligence), Some(Effect::ResistFire), Some(Effect::DamageFatigue), Some(Effect::FortifyHealth)],
        },
        Ingredient {
            name: String::from("Lavender Sprig"),
            id: String::from("000A792A"),
            description: String::from("Harvested from Lavender, a flower common in the Nibenay Basin."),
            value: 1u16,
            weight: 0.1f32,
            harvest_chance: 80.0f32,
        effects: [Some(Effect::RestorePersonality), Some(Effect::FortifyWillpower), Some(Effect::RestoreHealth), Some(Effect::DamageLuck)],
        },
        Ingredient {
            name: String::from("Leek"),
            id: String::from("00033680"),
            description: String::from("Food, found in several houses and dining halls. It can also be harvested from Leek Plants, which are found growing in a handful of farms."),
            value: 3u16,
            weight: 0.1f32,
            harvest_chance: 80.0f32,
        effects: [Some(Effect::RestoreFatigue), Some(Effect::FortifyAgility), Some(Effect::DamagePersonality), Some(Effect::DamageStrength)],
        },
        Ingredient {
            name: String::from("Lettuce"),
            id: String::from("00033681"),
            description: String::from("Food, widely found in houses and dining halls. It can also be harvested from Lettuce Plants, which are found growing on several farms."),
            value: 1u16,
            weight: 0.5f32,
            harvest_chance: 80.0f32,
        effects: [Some(Effect::RestoreFatigue), Some(Effect::RestoreLuck), Some(Effect::FireShield), Some(Effect::DamagePersonality)],
        },
        Ingredient {
            name: String::from("Lichor"),
            id: String::from("0007049E"),
            description: String::from("Harvested from bluish-purple colored Mana Bloom, a flower that is normally found only in Mankar Camoran's Paradise."),
            value: 3u16,
            weight: 0.1f32,
            harvest_chance: 80.0f32,
        effects: [Some(Effect::RestoreMagicka), None, None, None],
        },
        Ingredient {
            name: String::from("Mandrake Root"),
            id: String::from("00033683"),
            description: String::from("Harvested from Mandrake, a flower found growing in the Colovian Highlands and also near Bravil."),
            value: 1u16,
            weight: 0.1f32,
            harvest_chance: 80.0f32,
        effects: [Some(Effect::CureDisease), Some(Effect::ResistPoison), Some(Effect::DamageAgility), Some(Effect::FortifyWillpower)],
        },
        Ingredient {
            name: String::from("Milk Thistle Seeds"),
            id: String::from("000A792C"),
            description: String::from("Harvested from Milk Thistle, a flower found throughout mountainous regions (Jerall and Valus Mountains) and in some clusters in the Gold Coast."),
            value: 1u16,
            weight: 0.1f32,
            harvest_chance: 80.0f32,
        effects: [Some(Effect::Light), Some(Effect::FrostDamage), Some(Effect::CureParalysis), Some(Effect::Paralyze)],
        },
        Ingredient {
            name: String::from("Minotaur Horn"),
            id: String::from("00033568"),
            description: String::from("Collected from dead Minotaurs and Minotaur Lords, two types of monster found outdoors and in monster dungeons."),
            value: 55u16,
            weight: 5.0f32,
            harvest_chance: 0.0f32,
        effects: [Some(Effect::RestoreWillpower), Some(Effect::Burden), Some(Effect::FortifyEndurance), Some(Effect::ResistParalysis)],
        },
        Ingredient {
            name: String::from("Monkshood Root Pulp"),
            id: String::from("000A792E"),
            description: String::from("Harvested from Monkshood, a common flower in the Great Forest and Nibenay Basin."),
            value: 1u16,
            weight: 0.1f32,
            harvest_chance: 80.0f32,
        effects: [Some(Effect::RestoreStrength), Some(Effect::DamageIntelligence), Some(Effect::FortifyEndurance), Some(Effect::Burden)],
        },
        Ingredient {
            name: String::from("Morning Glory Root Pulp"),
            id: String::from("000A792F"),
            description: String::from("Harvested from Morning Glory, a flowering vine found growing on houses and walls in the West Weald and Heartlands."),
            value: 1u16,
            weight: 0.1f32,
            harvest_chance: 80.0f32,
        effects: [Some(Effect::Burden), Some(Effect::DamageWillpower), Some(Effect::FrostShield), Some(Effect::DamageMagicka)],
        },
        Ingredient {
            name: String::from("Mort Flesh"),
            id: String::from("00033685"),
            description: String::from("Collected from dead zombies, which are commonly found in all undead dungeons."),
            value: 10u16,
            weight: 2.0f32,
            harvest_chance: 0.0f32,
        effects: [Some(Effect::DamageFatigue), Some(Effect::DamageLuck), Some(Effect::FortifyHealth), Some(Effect::Silence)],
        },
        Ingredient {
            name: String::from("Motherwort Sprig"),
            id: String::from("000A7930"),
            description: String::from("Harvested from Motherwort, a flower common in most regions of Cyrodiil."),
            value: 1u16,
            weight: 0.1f32,
            harvest_chance: 80.0f32,
        effects: [Some(Effect::ResistPoison), Some(Effect::DamageFatigue), Some(Effect::Silence), Some(Effect::Invisibility)],
        },
        Ingredient {
            name: String::from("Mugwort Seeds"),
            id: String::from("000A7931"),
            description: String::from("Cannot be harvested or collected. The only way to obtain them is by purchasing them from alchemy vendors, who may randomly have some in stock."),
            value: 1u16,
            weight: 0.1f32,
            harvest_chance: 0.0f32,
        effects: [Some(Effect::RestoreHealth), None, None, None],
        },
        Ingredient {
            name: String::from("Mutton"),
            id: String::from("00033686"),
            description: String::from("Food, found in several houses and dining halls. Can also be collected from some (but not all) dead sheep."),
            value: 2u16,
            weight: 2.0f32,
            harvest_chance: 0.0f32,
        effects: [Some(Effect::FortifyHealth), Some(Effect::DamageFatigue), Some(Effect::Dispel), Some(Effect::DamageMagicka)],
        },
        Ingredient {
            name: String::from("Nightshade"),
            id: String::from("00033688"),
            description: String::from("Harvested from Nightshade Plants, a flower found in the West Weald."),
            value: 1u16,
            weight: 0.1f32,
            harvest_chance: 80.0f32,
        effects: [Some(Effect::DamageHealth), Some(Effect::Burden), Some(Effect::DamageLuck), Some(Effect::FortifyMagicka)],
        },
        Ingredient {
            name: String::from("Ogre's Teeth"),
            id: String::from("00033689"),
            description: String::from("Collected from dead Ogres, a type of monster found outdoors and in monster dungeons."),
            value: 75u16,
            weight: 3.0f32,
            harvest_chance: 0.0f32,
        effects: [Some(Effect::DamageIntelligence), Some(Effect::ResistParalysis), Some(Effect::ShockDamage), Some(Effect::FortifyStrength)],
        },
        Ingredient {
            name: String::from("Onion"),
            id: String::from("0003368A"),
            description: String::from("Food, found in many houses and dining halls."),
            value: 1u16,
            weight: 0.2f32,
            harvest_chance: 0.0f32,
        effects: [Some(Effect::RestoreFatigue), Some(Effect::WaterBreathing), Some(Effect::DetectLife), Some(Effect::DamageHealth)],
        },
        Ingredient {
            name: String::from("Orange"),
            id: String::from("0007588E"),
            description: String::from("Food, found in many houses and dining halls."),
            value: 2u16,
            weight: 0.2f32,
            harvest_chance: 0.0f32,
        effects: [Some(Effect::RestoreFatigue), Some(Effect::DetectLife), Some(Effect::Burden), Some(Effect::Shield)],
        },
        Ingredient {
            name: String::from("Pear"),
            id: String::from("0003368B"),
            description: String::from("Food, found in many houses and dining halls."),
            value: 1u16,
            weight: 0.2f32,
            harvest_chance: 0.0f32,
        effects: [Some(Effect::RestoreFatigue), Some(Effect::DamageSpeed), Some(Effect::FortifySpeed), Some(Effect::DamageHealth)],
        },
        Ingredient {
            name: String::from("Peony Seeds"),
            id: String::from("000A7932"),
            description: String::from("Harvested from Peonies, flowers common in the West Weald."),
            value: 1u16,
            weight: 0.1f32,
            harvest_chance: 80.0f32,
        effects: [Some(Effect::RestoreStrength), Some(Effect::DamageHealth), Some(Effect::DamageSpeed), Some(Effect::RestoreFatigue)],
        },
        Ingredient {
            name: String::from("Potato"),
            id: String::from("0003368C"),
            description: String::from("Food, widely found in houses and dining halls. Can also be harvested from Potato Plants, which are found growing on several farms."),
            value: 1u16,
            weight: 0.2f32,
            harvest_chance: 80.0f32,
        effects: [Some(Effect::RestoreFatigue), Some(Effect::Shield), Some(Effect::Burden), Some(Effect::FrostShield)],
        },
        Ingredient {
            name: String::from("Primrose Leaves"),
            id: String::from("000A7934"),
            description: String::from("Harvested from Primroses, which are flowers occasionally found growing outside various houses and inns."),
            value: 3u16,
            weight: 0.1f32,
            harvest_chance: 80.0f32,
        effects: [Some(Effect::RestoreWillpower), Some(Effect::RestorePersonality), Some(Effect::FortifyLuck), Some(Effect::DamageStrength)],
        },
        Ingredient {
            name: String::from("Pumpkin"),
            id: String::from("0003368D"),
            description: String::from("Food, widely found in houses and dining halls. Can also be harvested from Pumpkin Vines, which are found growing on some farms."),
            value: 2u16,
            weight: 5.0f32,
            harvest_chance: 80.0f32,
        effects: [Some(Effect::RestoreFatigue), Some(Effect::DamageAgility), Some(Effect::DamagePersonality), Some(Effect::DetectLife)],
        },
        Ingredient {
            name: String::from("Purgeblood SaltsVL"),
            id: String::from("xx001372"),
            description: String::from("Mined from Purgeblood Crystal Formations, which are only available as part of the Vile Lair download."),
            value: 0u16,
            weight: 0.4f32,
            harvest_chance: 100.0f32,
        effects: [Some(Effect::RestoreMagicka), Some(Effect::DamageHealth), Some(Effect::FortifyMagicka), Some(Effect::Dispel)],
        },
        Ingredient {
            name: String::from("Radish"),
            id: String::from("0003368E"),
            description: String::from("Food, found in many houses and dining halls. Can also be harvested from Radish Plants, which are found growing on several farms."),
            value: 1u16,
            weight: 0.1f32,
            harvest_chance: 80.0f32,
        effects: [Some(Effect::RestoreFatigue), Some(Effect::DamageEndurance), Some(Effect::Chameleon), Some(Effect::Burden)],
        },
        Ingredient {
            name: String::from("Rat Meat"),
            id: String::from("0003368F"),
            description: String::from("Collected from dead rats, a ubiquitous nuisance creature."),
            value: 1u16,
            weight: 0.5f32,
            harvest_chance: 0.0f32,
        effects: [Some(Effect::DamageFatigue), Some(Effect::DetectLife), Some(Effect::DamageMagicka), Some(Effect::Silence)],
        },
        Ingredient {
            name: String::from("Redwort Flower"),
            id: String::from("0002503A"),
            description: String::from("Harvested from Domica Redwort, a flower found growing in several clusters in Blackwood and sparsely throughout the West Weald."),
            value: 4u16,
            weight: 0.1f32,
            harvest_chance: 80.0f32,
        effects: [Some(Effect::ResistFrost), Some(Effect::CurePoison), Some(Effect::DamageHealth), Some(Effect::Invisibility)],
        },
        Ingredient {
            name: String::from("Rice"),
            id: String::from("00033690"),
            description: String::from("Food, generally found in grain sacks in kitchens and pantries."),
            value: 1u16,
            weight: 0.2f32,
            harvest_chance: 80.0f32,
        effects: [Some(Effect::RestoreFatigue), Some(Effect::Silence), Some(Effect::ShockShield), Some(Effect::DamageAgility)],
        },
        Ingredient {
            name: String::from("Root Pulp"),
            id: String::from("00033691"),
            description: String::from("Cannot be harvested or collected. Six guaranteed samples exist; otherwise found randomly in some containers."),
            value: 1u16,
            weight: 0.1f32,
            harvest_chance: 0.0f32,
        effects: [Some(Effect::CureDisease), Some(Effect::DamageWillpower), Some(Effect::FortifyStrength), Some(Effect::DamageIntelligence)],
        },
        Ingredient {
            name: String::from("Sacred Lotus Seeds"),
            id: String::from("000A7936"),
            description: String::from("Harvested from Sacred Lotus plants, which are flowers that grow in shallow water."),
            value: 1u16,
            weight: 0.1f32,
            harvest_chance: 80.0f32,
        effects: [Some(Effect::ResistFrost), Some(Effect::DamageHealth), Some(Effect::Feather), Some(Effect::Dispel)],
        },
        Ingredient {
            name: String::from("Scales"),
            id: String::from("00033692"),
            description: String::from("Collected from dead slaughterfish, an animal found in deep water, including pools in dungeons."),
            value: 5u16,
            weight: 0.1f32,
            harvest_chance: 0.0f32,
        effects: [Some(Effect::DamageWillpower), Some(Effect::WaterBreathing), Some(Effect::DamageHealth), Some(Effect::WaterWalking)],
        },
        Ingredient {
            name: String::from("Scamp Skin"),
            id: String::from("00033693"),
            description: String::from("Collected from dead Scamps, a type of Daedra common in the Planes of Oblivion."),
            value: 10u16,
            weight: 1.5f32,
            harvest_chance: 0.0f32,
        effects: [Some(Effect::DamageMagicka), Some(Effect::ResistShock), Some(Effect::ReflectDamage), Some(Effect::DamageHealth)],
        },
        Ingredient {
            name: String::from("Shepherd's Pie"),
            id: String::from("000B97E9"),
            description: String::from("Food, found in a few houses and dining halls. Also available from Eyja in Rosethorn Hall."),
            value: 0u16,
            weight: 1.0f32,
            harvest_chance: 0.0f32,
        effects: [Some(Effect::CureDisease), Some(Effect::Shield), Some(Effect::FortifyAgility), Some(Effect::Dispel)],
        },
        Ingredient {
            name: String::from("S'jirra's Famous Potato Bread"),
            id: String::from("00177A29"),
            description: String::from("Only available from S'jirra in Faregyl Inn after you have completed The Potato Snatcher. You receive from one to five loaves (based on level) upon completing the quest. You can also return to S'jirra repeatedly to buy more bread, which can then be used for alchemy."),
            value: 30u16,
            weight: 0.5f32,
            harvest_chance: 0.0f32,
        effects: [Some(Effect::DetectLife), Some(Effect::RestoreHealth), Some(Effect::DamageAgility), Some(Effect::DamageStrength)],
        },
        Ingredient {
            name: String::from("Somnalius Frond"),
            id: String::from("00033696"),
            description: String::from("Harvested from Somnalius Plants, which are found growing in the Great Forest."),
            value: 3u16,
            weight: 0.1f32,
            harvest_chance: 80.0f32,
        effects: [Some(Effect::RestoreSpeed), Some(Effect::DamageEndurance), Some(Effect::FortifyHealth), Some(Effect::Feather)],
        },
        Ingredient {
            name: String::from("Spiddal Stick"),
            id: String::from("00033697"),
            description: String::from("Harvested from Spiddal Stick plants, which are common in the Planes of Oblivion, but also tend to be hostile."),
            value: 2u16,
            weight: 0.1f32,
            harvest_chance: 50.0f32,
        effects: [Some(Effect::DamageHealth), Some(Effect::DamageMagicka), Some(Effect::FireDamage), Some(Effect::RestoreFatigue)],
        },
        Ingredient {
            name: String::from("St. Jahn's Wort Nectar"),
            id: String::from("000A7939"),
            description: String::from("Harvested from St. Jahn's Wort, a flower most commonly found in the Great Forest."),
            value: 5u16,
            weight: 0.1f32,
            harvest_chance: 80.0f32,
        effects: [Some(Effect::ResistShock), Some(Effect::DamageHealth), Some(Effect::CurePoison), Some(Effect::Chameleon)],
        },
        Ingredient {
            name: String::from("Steel-Blue Entoloma Cap"),
            id: String::from("0008446B"),
            description: String::from("Harvested from Steel-Blue Entoloma, a mushroom that is common in the Great Forest."),
            value: 1u16,
            weight: 0.1f32,
            harvest_chance: 50.0f32,
        effects: [Some(Effect::RestoreMagicka), Some(Effect::FireDamage), Some(Effect::ResistFrost), Some(Effect::Burden)],
        },
        Ingredient {
            name: String::from("Stinkhorn Cap"),
            id: String::from("0008446D"),
            description: String::from("Harvested from Stinkhorn, a mushroom that is found in Blackwood."),
            value: 3u16,
            weight: 0.1f32,
            harvest_chance: 50.0f32,
        effects: [Some(Effect::DamageHealth), Some(Effect::RestoreMagicka), Some(Effect::WaterWalking), Some(Effect::Invisibility)],
        },
        Ingredient {
            name: String::from("Strawberry"),
            id: String::from("00033699"),
            description: String::from("Food, widely found in houses and dining halls. It can also be harvested from Strawberry Bushes found on some farms and in the wild in the West Weald."),
            value: 1u16,
            weight: 0.1f32,
            harvest_chance: 80.0f32,
        effects: [Some(Effect::RestoreFatigue), Some(Effect::CurePoison), Some(Effect::DamageHealth), Some(Effect::ReflectDamage)],
        },
        Ingredient {
            name: String::from("Summer Bolete Cap"),
            id: String::from("00084470"),
            description: String::from("Harvested from Summer Bolete, a mushroom found in the Great Forest and Nibenay Valley."),
            value: 1u16,
            weight: 0.1f32,
            harvest_chance: 50.0f32,
        effects: [Some(Effect::RestoreAgility), Some(Effect::Shield), Some(Effect::DamagePersonality), Some(Effect::DamageEndurance)],
        },
        Ingredient {
            name: String::from("Sweetcake"),
            id: String::from("0003369A"),
            description: String::from("Food, found in a few houses and dining halls. Sweetcakes are less common than Sweetrolls."),
            value: 1u16,
            weight: 0.2f32,
            harvest_chance: 0.0f32,
        effects: [Some(Effect::RestoreFatigue), Some(Effect::Feather), Some(Effect::RestoreHealth), Some(Effect::Burden)],
        },
        Ingredient {
            name: String::from("Sweetroll"),
            id: String::from("0003369B"),
            description: String::from("Food, found in several houses and dining halls."),
            value: 1u16,
            weight: 0.2f32,
            harvest_chance: 0.0f32,
        effects: [Some(Effect::RestoreFatigue), Some(Effect::ResistDisease), Some(Effect::DamagePersonality), Some(Effect::FortifyHealth)],
        },
        Ingredient {
            name: String::from("Taproot"),
            id: String::from("000AF06E"),
            description: String::from("Collected from dead Spriggans, a type of monster found outdoors and in monster dungeons."),
            value: 1u16,
            weight: 0.3f32,
            harvest_chance: 0.0f32,
        effects: [Some(Effect::RestoreLuck), Some(Effect::DamageEndurance), Some(Effect::ResistPoison), Some(Effect::ShockShield)],
        },
        Ingredient {
            name: String::from("Tiger Lily Nectar"),
            id: String::from("000A792B"),
            description: String::from("Harvested from both Tiger Lilies and Lily of the Valleys, two types of flower that are most commonly found in the Great Forest."),
            value: 3u16,
            weight: 0.1f32,
            harvest_chance: 80.0f32,
        effects: [Some(Effect::RestoreEndurance), Some(Effect::DamageStrength), Some(Effect::WaterWalking), Some(Effect::DamageWillpower)],
        },
        Ingredient {
            name: String::from("Tinder Polypore Cap"),
            id: String::from("0008446F"),
            description: String::from("Harvested from Tinder Polypore, a mushroom common in the Valus Mountains."),
            value: 1u16,
            weight: 0.1f32,
            harvest_chance: 50.0f32,
        effects: [Some(Effect::RestoreWillpower), Some(Effect::ResistDisease), Some(Effect::Invisibility), Some(Effect::DamageMagicka)],
        },
        Ingredient {
            name: String::from("Tobacco"),
            id: String::from("0003369D"),
            description: String::from("Technically treated as a food and can be found in a few houses. It can also be harvested from Tobacco Plants, which are found on several farms."),
            value: 5u16,
            weight: 0.1f32,
            harvest_chance: 80.0f32,
        effects: [Some(Effect::RestoreFatigue), Some(Effect::ResistParalysis), Some(Effect::DamageMagicka), Some(Effect::Dispel)],
        },
        Ingredient {
            name: String::from("Tomato"),
            id: String::from("0003369E"),
            description: String::from("Food, widely found in houses and dining halls. It can also be harvested from Tomato Plants, which are found growing on many farms."),
            value: 2u16,
            weight: 0.2f32,
            harvest_chance: 80.0f32,
        effects: [Some(Effect::RestoreFatigue), Some(Effect::DetectLife), Some(Effect::Burden), Some(Effect::Shield)],
        },
        Ingredient {
            name: String::from("Troll Fat"),
            id: String::from("00026B5C"),
            description: String::from("Collected from dead Trolls, a type of monster found outdoors and in monster dungeons."),
            value: 25u16,
            weight: 2.0f32,
            harvest_chance: 0.0f32,
        effects: [Some(Effect::DamageAgility), Some(Effect::FortifyPersonality), Some(Effect::DamageWillpower), Some(Effect::DamageHealth)],
        },
        Ingredient {
            name: String::from("Vampire Dust*"),
            id: String::from("00009182"),
            description: String::from("Collected from dead Vampires, found in a range of vampire dungeons. There is also a rare variant listed below."),
            value: 50u16,
            weight: 0.2f32,
            harvest_chance: 0.0f32,
        effects: [Some(Effect::Silence), Some(Effect::ResistDisease), Some(Effect::FrostDamage), Some(Effect::Invisibility)],
        },
        Ingredient {
            name: String::from("Venison"),
            id: String::from("0002229B"),
            description: String::from("Food, found in several houses and dining halls. It can also be collected from dead deer, which are animals found outdoors throughout Cyrodiil."),
            value: 1u16,
            weight: 2.0f32,
            harvest_chance: 0.0f32,
        effects: [Some(Effect::RestoreHealth), Some(Effect::Feather), Some(Effect::DamageHealth), Some(Effect::Chameleon)],
        },
        Ingredient {
            name: String::from("Viper's Bugloss Leaves"),
            id: String::from("000A793B"),
            description: String::from("Harvested from Viper's Bugloss, a flower which is abundant in the Great Forest."),
            value: 1u16,
            weight: 0.1f32,
            harvest_chance: 80.0f32,
        effects: [Some(Effect::ResistParalysis), Some(Effect::NightEye), Some(Effect::Burden), Some(Effect::CureParalysis)],
        },
        Ingredient {
            name: String::from("Void Salts"),
            id: String::from("0003369F"),
            description: String::from("Collected from dead Storm Atronachs, a type of Daedra common in the Planes of Oblivion."),
            value: 30u16,
            weight: 0.4f32,
            harvest_chance: 0.0f32,
        effects: [Some(Effect::RestoreMagicka), Some(Effect::DamageHealth), Some(Effect::FortifyMagicka), Some(Effect::Dispel)],
        },
        Ingredient {
            name: String::from("Water Hyacinth Nectar"),
            id: String::from("000A793C"),
            description: String::from("Harvested from Water Hyacinth, a flower found growing in shallow water."),
            value: 2u16,
            weight: 0.1f32,
            harvest_chance: 80.0f32,
        effects: [Some(Effect::DamageLuck), Some(Effect::DamageFatigue), Some(Effect::RestoreMagicka), Some(Effect::FortifyMagicka)],
        },
        Ingredient {
            name: String::from("Watermelon"),
            id: String::from("000336A0"),
            description: String::from("Food, found in several houses and dining halls. It can also be harvested from Watermelon Vines, which grow on a few farms."),
            value: 2u16,
            weight: 5.0f32,
            harvest_chance: 80.0f32,
        effects: [Some(Effect::RestoreFatigue), Some(Effect::Light), Some(Effect::Burden), Some(Effect::DamageHealth)],
        },
        Ingredient {
            name: String::from("Wheat Grain"),
            id: String::from("000336A1"),
            description: String::from("Food, found in grain sacks in kitchens and pantries. It can also be harvested from Wheat Stalks, which grow on a few farms."),
            value: 1u16,
            weight: 0.2f32,
            harvest_chance: 80.0f32,
        effects: [Some(Effect::RestoreFatigue), Some(Effect::DamageMagicka), Some(Effect::FortifyHealth), Some(Effect::DamagePersonality)],
        },
        Ingredient {
            name: String::from("White Seed Pod"),
            id: String::from("000336A2"),
            description: String::from("Harvested from Goldenrod, a flower found in the Gold Coast."),
            value: 5u16,
            weight: 0.1f32,
            harvest_chance: 80.0f32,
        effects: [Some(Effect::RestoreStrength), Some(Effect::WaterBreathing), Some(Effect::Silence), Some(Effect::Light)],
        },
        Ingredient {
            name: String::from("Wisp Stalk Caps"),
            id: String::from("0006251F"),
            description: String::from("Harvested from Wisp Stalks, a mushroom that is only found growing underground (i.e., in caves and mines)."),
            value: 1u16,
            weight: 0.1f32,
            harvest_chance: 33.0f32,
        effects: [Some(Effect::DamageHealth), Some(Effect::DamageWillpower), Some(Effect::DamageIntelligence), Some(Effect::FortifySpeed)],
        },
        Ingredient {
            name: String::from("Wormwood Leaves"),
            id: String::from("000A793E"),
            description: String::from("Harvested from Wormwood, a plant found growing in the Jerall Mountains."),
            value: 2u16,
            weight: 0.1f32,
            harvest_chance: 80.0f32,
        effects: [Some(Effect::FortifyFatigue), Some(Effect::Invisibility), Some(Effect::DamageHealth), Some(Effect::DamageMagicka)],
        },
        // Shivering Isles
        Ingredient {
            name: String::from("Alocasia Fruit"),
            id: String::from("0001AE7A"),
            description: String::from("Harvested from Alocasia plants, found in Mania."),
            value: 1u16,
            weight: 0.25f32,
            harvest_chance: 80.0f32,
        effects: [Some(Effect::RestoreFatigue), Some(Effect::Light), Some(Effect::RestoreHealth), Some(Effect::DamageMagicka)],
        },
        Ingredient {
            name: String::from("Ashen Remains"),
            id: String::from("00081A68"),
            description: String::from("Created from bones using the Crematorium in Ebrocca."),
            value: 5u16,
            weight: 0.8f32,
            harvest_chance: 0.0f32,
        effects: [Some(Effect::FortifyFatigue), Some(Effect::DamageLuck), Some(Effect::Silence), Some(Effect::WeaknessToFire)],
        },
        Ingredient {
            name: String::from("Aster Bloom Core"),
            id: String::from("0001B035"),
            description: String::from("Harvested from Aster Bloom plants, found in Mania."),
            value: 1u16,
            weight: 0.1f32,
            harvest_chance: 80.0f32,
        effects: [Some(Effect::RestoreAgility), Some(Effect::Dispel), Some(Effect::Shield), Some(Effect::Burden)],
        },
        Ingredient {
            name: String::from("Black Tar"),
            id: String::from("0003BABD"),
            description: String::from("Harvested from Dementia variety Mushroom Tree Saplings and from Black Tar plants."),
            value: 1u16,
            weight: 0.1f32,
            harvest_chance: 80.0f32,
        effects: [Some(Effect::DamageFatigue), Some(Effect::DamageSpeed), Some(Effect::DamageHealth), Some(Effect::ShockDamage)],
        },
        Ingredient {
            name: String::from("Blister Pod Cap"),
            id: String::from("0001F3AA"),
            description: String::from("Harvested from Blister Pod plants, which are found in Dementia."),
            value: 1u16,
            weight: 0.1f32,
            harvest_chance: 66.0f32,
        effects: [Some(Effect::RestoreMagicka), Some(Effect::FortifyMagicka), Some(Effect::NightEye), Some(Effect::Invisibility)],
        },
        Ingredient {
            name: String::from("Bone Marrow"),
            id: String::from("00044E61"),
            description: String::from("Found on Shambles (50% chance they may yield Bone Shard instead). Also called \"Shambles Marrow.\""),
            value: 2u16,
            weight: 0.1f32,
            harvest_chance: 0.0f32,
        effects: [Some(Effect::DamageHealth), Some(Effect::FrostDamage), Some(Effect::DamageMagicka), Some(Effect::Paralyze)],
        },
        Ingredient {
            name: String::from("Bone Shard"),
            id: String::from("00052443"),
            description: String::from("Found on Shambles (50% chance they may yield Bone Marrow instead)."),
            value: 1u16,
            weight: 0.3f32,
            harvest_chance: 0.0f32,
        effects: [Some(Effect::RestoreWillpower), Some(Effect::FrostShield), Some(Effect::DamageMagicka), Some(Effect::DamageLuck)],
        },
        Ingredient {
            name: String::from("Congealed Putrescence"),
            id: String::from("000402E9"),
            description: String::from("Harvested from Putrid Gigantea plants, found in Dementia."),
            value: 1u16,
            weight: 0.1f32,
            harvest_chance: 66.0f32,
        effects: [Some(Effect::RestoreStrength), Some(Effect::FireDamage), Some(Effect::RestoreMagicka), Some(Effect::DamageHealth)],
        },
        Ingredient {
            name: String::from("Elytra Ichor"),
            id: String::from("00044E5D"),
            description: String::from("Found on Elytras."),
            value: 3u16,
            weight: 0.1f32,
            harvest_chance: 0.0f32,
        effects: [Some(Effect::RestoreMagicka), Some(Effect::Burden), Some(Effect::Chameleon), Some(Effect::Silence)],
        },
        Ingredient {
            name: String::from("Flame Stalk 0001B6AE /"),
            id: String::from("00097613"),
            description: String::from("Harvested from Flame Stalk plants, found in Mania caves."),
            value: 1u16,
            weight: 0.1f32,
            harvest_chance: 33.0f32,
        effects: [Some(Effect::RestoreHealth), Some(Effect::FireDamage), Some(Effect::FrostShield), Some(Effect::Invisibility)],
        },
        Ingredient {
            name: String::from("Fungus Stalk"),
            id: String::from("00019529"),
            description: String::from("Harvested from Fungus Stalk plants, found in Dementia."),
            value: 1u16,
            weight: 0.1f32,
            harvest_chance: 50.0f32,
        effects: [Some(Effect::RestoreStrength), Some(Effect::WaterWalking), Some(Effect::FortifyHealth), Some(Effect::RestoreMagicka)],
        },
        Ingredient {
            name: String::from("Gnarl Bark"),
            id: String::from("00044E5E"),
            description: String::from("Found on Gnarls."),
            value: 1u16,
            weight: 0.1f32,
            harvest_chance: 0.0f32,
        effects: [Some(Effect::RestoreEndurance), Some(Effect::Shield), Some(Effect::FireShield), Some(Effect::DamageHealth)],
        },
        Ingredient {
            name: String::from("Grummite Eggs"),
            id: String::from("0001AE82"),
            description: String::from("Harvested from Grummite Egg Mounds and Grummite Egg Sacs, found primarily in Dementia. May also be found on Grummites (25% chance)."),
            value: 1u16,
            weight: 0.5f32,
            harvest_chance: 80.0f32,
        effects: [Some(Effect::DamageMagicka), Some(Effect::Dispel), Some(Effect::Chameleon), Some(Effect::Silence)],
        },
        Ingredient {
            name: String::from("Hound Tooth"),
            id: String::from("00044E62"),
            description: String::from("Found on Skinned Hounds."),
            value: 1u16,
            weight: 0.1f32,
            harvest_chance: 0.0f32,
        effects: [Some(Effect::CurePoison), Some(Effect::DetectLife), Some(Effect::Burden), Some(Effect::Invisibility)],
        },
        Ingredient {
            name: String::from("Hunger Tongue"),
            id: String::from("00044E60"),
            description: String::from("Found on Hungers."),
            value: 4u16,
            weight: 0.1f32,
            harvest_chance: 0.0f32,
        effects: [Some(Effect::CurePoison), Some(Effect::CureDisease), Some(Effect::FireDamage), Some(Effect::FortifyMagicka)],
        },
        Ingredient {
            name: String::from("Hydnum Azure Giant Spore"),
            id: String::from("0003BAD3"),
            description: String::from("Harvested from Hydnum Azure plants, found in Mania."),
            value: 1u16,
            weight: 0.5f32,
            harvest_chance: 66.0f32,
        effects: [Some(Effect::RestoreEndurance), Some(Effect::DetectLife), Some(Effect::FortifyHealth), Some(Effect::FrostShield)],
        },
        Ingredient {
            name: String::from("Letifer Orca Digestive Slime"),
            id: String::from("0003E632"),
            description: String::from("Harvested from Letifer Orca Planta, found in Dementia. Also called simply \"Digestive Slime.\""),
            value: 1u16,
            weight: 0.1f32,
            harvest_chance: 66.0f32,
        effects: [Some(Effect::DamageHealth), Some(Effect::DamageFatigue), Some(Effect::DamageMagicka), Some(Effect::RestoreFatigue)],
        },
        Ingredient {
            name: String::from("Red Kelp Gas Bladder"),
            id: String::from("0001A16E"),
            description: String::from("Harvested from Red Kelp, found in Mania. Also called simply \"Gas Bladder.\""),
            value: 1u16,
            weight: 0.1f32,
            harvest_chance: 50.0f32,
        effects: [Some(Effect::RestoreSpeed), Some(Effect::WaterBreathing), Some(Effect::CureDisease), Some(Effect::FortifyMagicka)],
        },
        Ingredient {
            name: String::from("Rot Scale"),
            id: String::from("0001B6B2"),
            description: String::from("Harvested from Rot Scale, found in Dementia caves."),
            value: 1u16,
            weight: 0.1f32,
            harvest_chance: 33.0f32,
        effects: [Some(Effect::Burden), Some(Effect::DamageHealth), Some(Effect::Silence), Some(Effect::Paralyze)],
        },
        Ingredient {
            name: String::from("Scalon Fin"),
            id: String::from("00044E5F"),
            description: String::from("Found on Scalons."),
            value: 1u16,
            weight: 0.1f32,
            harvest_chance: 0.0f32,
        effects: [Some(Effect::WaterBreathing), Some(Effect::DamageHealth), Some(Effect::ShockDamage), Some(Effect::Burden)],
        },
        Ingredient {
            name: String::from("Screaming Maw"),
            id: String::from("0001B6B0"),
            description: String::from("Harvested from Screaming Maw plants, found in Mania caves."),
            value: 1u16,
            weight: 0.1f32,
            harvest_chance: 66.0f32,
        effects: [Some(Effect::RestoreWillpower), Some(Effect::DetectLife), Some(Effect::Chameleon), Some(Effect::RestoreHealth)],
        },
        Ingredient {
            name: String::from("Smoked Baliwog Leg"),
            id: String::from("0007D048"),
            description: String::from("Found as food in shops and houses."),
            value: 2u16,
            weight: 1.0f32,
            harvest_chance: 0.0f32,
        effects: [Some(Effect::RestoreFatigue), Some(Effect::Feather), Some(Effect::RestoreHealth), Some(Effect::DamageFatigue)],
        },
        Ingredient {
            name: String::from("Swamp Tentacle"),
            id: String::from("000413DC"),
            description: String::from("Harvested from Swamp Tentacle plants, found in Dementia."),
            value: 2u16,
            weight: 0.2f32,
            harvest_chance: 80.0f32,
        effects: [Some(Effect::RestorePersonality), Some(Effect::WaterBreathing), Some(Effect::WaterWalking), Some(Effect::FortifyHealth)],
        },
        Ingredient {
            name: String::from("Thorn Hook"),
            id: String::from("0001B6B1"),
            description: String::from("Harvested from Thorn Hook plants, found in Dementia caves."),
            value: 1u16,
            weight: 0.1f32,
            harvest_chance: 33.0f32,
        effects: [Some(Effect::DamageHealth), Some(Effect::DamageLuck), Some(Effect::RestoreMagicka), Some(Effect::FortifyHealth)],
        },
        Ingredient {
            name: String::from("Unrefined Greenmote"),
            id: String::from("00077AD9"),
            description: String::from("Harvested from Mania variety Mushroom Tree Saplings."),
            value: 1u16,
            weight: 0.5f32,
            harvest_chance: 80.0f32,
        effects: [Some(Effect::DrainFatigue), Some(Effect::DrainHealth), Some(Effect::DrainMagicka), Some(Effect::DrainIntelligence)],
        },
        Ingredient {
            name: String::from("Void Essence"),
            id: String::from("00044E5C"),
            description: String::from("Found on Flesh Atronachs."),
            value: 50u16,
            weight: 0.2f32,
            harvest_chance: 0.0f32,
        effects: [Some(Effect::RestoreHealth), Some(Effect::FortifyHealth), Some(Effect::FortifyStrength), Some(Effect::FortifyEndurance)],
        },
        Ingredient {
            name: String::from("Watcher's Eye"),
            id: String::from("0001B6AF"),
            description: String::from("Harvested from Watcher's Eye plants, which grow in Dementia caves."),
            value: 1u16,
            weight: 0.2f32,
            harvest_chance: 80.0f32,
        effects: [Some(Effect::RestoreIntelligence), Some(Effect::FortifyMagicka), Some(Effect::Light), Some(Effect::ReflectSpell)],
        },
        Ingredient {
            name: String::from("Water Root Pod Pit"),
            id: String::from("00040CAF"),
            description: String::from("Harvested from Water Root Pod plants, which grow in Dementia. Also called simply \"Pod Pit.\""),
            value: 3u16,
            weight: 1.0f32,
            harvest_chance: 80.0f32,
        effects: [Some(Effect::RestoreHealth), Some(Effect::ResistFire), Some(Effect::FireShield), Some(Effect::WaterBreathing)],
        },
        Ingredient {
            name: String::from("Wisp Core"),
            id: String::from("0007D04E"),
            description: String::from("Harvested from Root Stalks, which grow in Dementia and Mania caves."),
            value: 2u16,
            weight: 0.1f32,
            harvest_chance: 25.0f32,
        effects: [Some(Effect::RestoreIntelligence), Some(Effect::Burden), Some(Effect::Light), Some(Effect::Chameleon)],
        },
        Ingredient {
            name: String::from("Withering Moon"),
            id: String::from("0001B6B3"),
            description: String::from("Harvested from Withering Moon plants, which grow in Dementia caves."),
            value: 1u16,
            weight: 0.1f32,
            harvest_chance: 33.0f32,
        effects: [Some(Effect::RestoreMagicka), Some(Effect::Shield), Some(Effect::CureDisease), Some(Effect::ReflectSpell)],
        },
        Ingredient {
            name: String::from("Worm's Head Cap"),
            id: String::from("0001B5AA"),
            description: String::from("Harvested from Worm's Head plants, which grow in Mania."),
            value: 1u16,
            weight: 0.2f32,
            harvest_chance: 80.0f32,
        effects: [Some(Effect::RestoreLuck), Some(Effect::NightEye), Some(Effect::FortifyFatigue), Some(Effect::Paralyze)],
        },
    ]
}
